// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5bNDQw4MuoeSqEsdcvbfQ0-ZTAXoTTuY',
    appId: '1:408655926782:web:8cefe9c16b059134a1dcaf',
    messagingSenderId: '408655926782',
    projectId: 'spot-workout-logger',
    authDomain: 'spot-workout-logger.firebaseapp.com',
    storageBucket: 'spot-workout-logger.appspot.com',
    measurementId: 'G-MWLC1GF66R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdIuf97lUPNAEhS_OLBz1mAZfLV3uqLek',
    appId: '1:408655926782:android:37519ab54bbdf809a1dcaf',
    messagingSenderId: '408655926782',
    projectId: 'spot-workout-logger',
    storageBucket: 'spot-workout-logger.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQzWflLrWuUQRdEIOcvKkmr4-rMzrFeuE',
    appId: '1:408655926782:ios:be7f02a71dc5ef36a1dcaf',
    messagingSenderId: '408655926782',
    projectId: 'spot-workout-logger',
    storageBucket: 'spot-workout-logger.appspot.com',
    iosClientId: '408655926782-njd20dfohr4g5kj0smrqbfnm017gr34l.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQzWflLrWuUQRdEIOcvKkmr4-rMzrFeuE',
    appId: '1:408655926782:ios:be7f02a71dc5ef36a1dcaf',
    messagingSenderId: '408655926782',
    projectId: 'spot-workout-logger',
    storageBucket: 'spot-workout-logger.appspot.com',
    iosClientId: '408655926782-njd20dfohr4g5kj0smrqbfnm017gr34l.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotApp',
  );
}
